name: Tests

on: [push]

jobs:
  multi-fs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Update Rust to latest
        run: ~/.cargo/bin/rustup update

      - name: Create filesystems
        # f2fs and exfat modules are in linux-modules-extra-azure
        # and cannot be installed reliably:
        # https://github.com/actions/runner-images/issues/7587
        run: xcp-bin/tests/scripts/make-filesystems.sh ext2 ext4 xfs btrfs ntfs fat zfs

      - name: Run tests on ext2
        run: cargo test --workspace --features=test_no_extents,test_no_reflink
        working-directory: /fs/ext2/src

      - name: Run tests on ext4
        run: cargo test --workspace --features=test_no_reflink
        working-directory: /fs/ext4/src

      - name: Run tests on XFS
        run: cargo test --workspace
        working-directory: /fs/xfs/src

      - name: Run tests on btrfs
        run: cargo test --workspace
        working-directory: /fs/btrfs/src

      - name: Run tests on ntfs
        run: cargo test --workspace --features=test_no_extents,test_no_sparse,test_no_reflink
        working-directory: /fs/ntfs/src

      - name: Run tests on fat
        run: cargo test --workspace --features=test_no_extents,test_no_sparse,test_no_sockets,test_no_symlinks,test_no_xattr,test_no_reflink
        working-directory: /fs/fat/src

      - name: Run tests on ZFS
        run: cargo test --workspace --features=test_no_extents,test_no_reflink,test_no_sparse
        working-directory: /fs/zfs/src

  expensive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Update Rust to latest
        run: ~/.cargo/bin/rustup update

      - name: Run expensive tests
        # Assume we're running on ext4
        run: ~/.cargo/bin/cargo test --workspace --features=test_no_reflink,test_run_expensive

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash /dev/stdin -y

      - name: Update Rust (installer may lag behind)
        run: ~/.cargo/bin/rustup update

      - name: Run all tests
        run: ~/.cargo/bin/cargo test --workspace --features=test_no_reflink,test_no_sockets,test_run_expensive

  freebsd:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v3

     - uses: vmactions/freebsd-vm@v1
       with:
         usesh: true
         prepare: |
           pkg install -y curl
         run: |
           curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh /dev/stdin -y
           ~/.cargo/bin/cargo test --workspace --features=test_no_reflink,test_no_sockets,test_run_expensive
           rm -rf target/generated_filetree/
