name: Tests

on: [push]

jobs:
  freebsd:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v3

     - uses: vmactions/freebsd-vm@v1
       with:
         usesh: true
         run: |
           echo test content > file1.txt
           touch file2.txt
           chmod 0 file2.txt

           ls -l file*txt
           cp -v file1.txt file2.txt
           ls -l file*txt
